### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by CsabaZz** [snpscrn/sdk-android#2]
Sorry to keep you guys in tight hand, but I really would like to use this SDK. :) If I call thr SDK init method, it crashes with the following exception:

`10-31 20:01:56.426 27475-27475/com.miomni.Miomni E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.miomni.Miomni, PID: 27475
                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/Authenticator;
                                                                       at com.snapscreen.sdk.SnapscreenKit.init(SnapscreenKit.java:190)
                                                                       at com.miomni.Sportsbook.ui.activities.ModuleSelectorActivity.createContentView(ModuleSelectorActivity.java:383)
                                                                       at com.miomni.Sportsbook.ui.activities.ModuleSelectorActivity.onCreate(ModuleSelectorActivity.java:120)
                                                                       at android.app.Activity.performCreate(Activity.java:6955)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.Authenticator" on path: DexPathList[[zip file "/data/app/com.miomni.Miomni-2/base.apk"],nativeLibraryDirectories=[/data/app/com.miomni.Miomni-2/lib/arm64, /system/fake-libs64, /data/app/com.miomni.Miomni-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.snapscreen.sdk.SnapscreenKit.init(SnapscreenKit.java:190) 
                                                                       at com.miomni.Sportsbook.ui.activities.ModuleSelectorActivity.createContentView(ModuleSelectorActivity.java:383) 
                                                                       at com.miomni.Sportsbook.ui.activities.ModuleSelectorActivity.onCreate(ModuleSelectorActivity.java:120) 
                                                                       at android.app.Activity.performCreate(Activity.java:6955) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) `

Can you advise please?

**Comment by CsabaZz** [comment]
Adding the long dependency list solved this problem, but I'm unsure why it is needed. Anyway, now I get the following exception:

`Caused by: java.lang.IllegalStateException: Native library not found (OS: Linux, Arch: aarch64, VM: Dalvik, Lib: libsnapscreen_matching_client_android.so)
                                                                     at com.snapscreen.matching.client.SnapScreenClientJNILoader.loadLibrary(SnapScreenClientJNILoader.java:87)
                                                                     at com.snapscreen.matching.client.SnapScreenClientJNILoader.access$100(SnapScreenClientJNILoader.java:25)
                                                                     at com.snapscreen.matching.client.SnapScreenClientJNILoader$1.run(SnapScreenClientJNILoader.java:39)
                                                                     at java.security.AccessController.doPrivileged(AccessController.java:41)
                                                                     at com.snapscreen.matching.client.SnapScreenClientJNILoader.<clinit>(SnapScreenClientJNILoader.java:33)
                                                                     at java.lang.Class.classForName(Native Method) 
                                                                     at java.lang.Class.forName(Class.java:400) 
                                                                     at java.lang.Class.forName(Class.java:326) 
                                                                     at com.snapscreen.matching.client.SnapScreenClientUtils.<clinit>(SnapScreenClientUtils.java:40) 
                                                                     at com.snapscreen.matching.client.SnapScreenClientUtils.newFeaturesExtractor(SnapScreenClientUtils.java:65) 
                                                                     at com.snapscreen.sdk.matching.Matching.<init>(Matching.java:48) 
                                                                     at com.snapscreen.sdk.ui.internal.SnapPresenter.<init>(SnapPresenter.java:72) 
                                                                     at com.snapscreen.sdk.ui.internal.SnapFragment.onCreateView(SnapFragment.java:183) 
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
                                                                     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
                                                                     at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231) 
                                                                     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181) 
                                                                     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192) 
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572) 
                                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177) 
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256) 
                                                                     at android.app.Activity.performStart(Activity.java:6972) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) `

**Comment by CsabaZz** [comment]
In the aar file, I can find the SO file only for the "armeabi-v7a" ABI. Where/how can I download the others?
